name: sistema_monitoramento
description: Sistema de monitoramento com Dart puro
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  mysql1: ^0.20.0
  http: ^1.1.0              
  dart_jsonwebtoken: ^2.12.0 
